name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  BRANCH_NAME:
    required: true
    description: "the name of the current branch"
  ENVIRONMENT_NAME:
    required: true
    description: "the name of the environment variable"
  BUCKET_NAME:
    required: true
    description: 'AWS S3 bucket to push the data'
  SERVICE_NAME:
    required: true
    description: 'Name of the service using this action'
  REGION:
    required: true
    description: 'AWS S3 bucket region'
  CONFIG_PATH:
    required: true
    description: 'Path to config file used in action'
  TARGET_BRANCH:
    required: true
    description: 'Target branch of PR'
  EVENT_TYPE:
    required: true
    description: 'The event type'
runs:
  using: 'node16'
  main: 'dist/index.js'
